### ISSUE TITLE
Uputronics fudges

### ISSUE THREAD

**Issue by snyggapa** [ntpsec/stratum-1-microserver-howto#1]
Hi. Just to say that I have 2 x PI 3b+ with uputronics GPS hats running on stretch lite , it works well - any my knowledge of PIs up until a couple of days ago was zero so this guide and script were very welcome.

The only thing I have changed is in the ntp.conf , setting the pool servers to be UK and the following refclock line to add a time1 offset otherwise the GPS provided time is offset by ~120 ms. 

refclock shm unit 0 refid GPS time1 +0.120

I assume this is the correct way to place a "fudge", and the same fudge seems to hold true for both units give or take a couple of milliseconds, however even so, I have 2 identical units places next to each other and one of them prefers an external NTP source over the GPS which is interesting, although from my understanding the PPS is being used so the tick should be accurate? 

*SHM(1)          .PPS.            0 l   61   64  377   0.0000   0.0864   0.0067
-SHM(0)          .GPS.            0 l   29   64  377   0.0000   0.3343   3.2631
 uk.pool.ntp.org .POOL.          16 p    -  256    0   0.0000   0.0000   0.0019
-139.59.199.215  81.174.136.35    2 u   51   64  377   2.2418   0.0287   0.9456
+158.43.128.33   .PPS.            1 u   39   64  377   1.4592   0.1109   0.5944

and

*SHM(1)          .PPS.            0 l   15   64  377   0.0000  -0.5866   0.4705
+SHM(0)          .GPS.            0 l   41   64  377   0.0000   1.5996   1.4535
 uk.pool.ntp.org .POOL.          16 p    - 1024    0   0.0000   0.0000   0.0019
+ntp0.pipex.net  .PPS.            1 u   32   64  377   1.8097  -0.2479   0.2884

One question though the SHM PPS source on both is marked as * instead of o in the tally column - does that affect the usage of PPS in the determination?

Thanks

Steve

**Comment by selsky** [comment]
Moved to https://gitlab.com/NTPsec/www/issues/9
