### ISSUE TITLE
The `clockmaker` script is missing identifiers for more recent Raspberry Pi models

### ISSUE THREAD

**Issue by grempe** [ntpsec/stratum-1-microserver-howto#2]
The model revision ID's are missing some recent models, causing the `clockmaker` script to fail on running `clockmaker --config`:

https://github.com/ntpsec/stratum-1-microserver-howto/blob/master/clockmaker#L67

The `New Style` additional revision codes are listed here:

https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

Without the addition of the revision code for my Raspberry Pi Model 3B+ this script fails when first used:

```
pi@raspberrypi:~ $ sudo ./clockmaker --config
SBC type is Raspberry Pi
Can't identify SBC version
```

Adding the following entry allowed the script to work:

```
"a020d3" : "Pi 3 Model B+",
```

**Comment by selsky** [comment]
Moved to https://gitlab.com/NTPsec/www/issues/10
