### ISSUE TITLE
HOWTO file website appears out of sync with website source

### ISSUE THREAD

**Issue by grempe** [ntpsec/stratum-1-microserver-howto#3]
The HOWTO found at:

https://www.ntpsec.org/white-papers/stratum-1-microserver-howto/

Seems to be using an older version of the file found at:

https://github.com/ntpsec/stratum-1-microserver-howto/blob/master/index.txt#L878

Note specifically that line in both files:

Source:

```
# ./ntpsec/build/main/ntpd/ntpd -g -c ntp.conf
```

Website:
(references the wrong location for the config file)

```
# ./ntpsec/build/main/ntpd/ntpd -g -c ntpsec/ntp.conf
```

**Comment by selsky** [comment]
Moved to https://gitlab.com/NTPsec/www/issues/11
