### ISSUE TITLE
The HOWTO indicates it will set `PermitRootLogin` to `no`, but instead sets `without-password` 

### ISSUE THREAD

**Issue by grempe** [ntpsec/stratum-1-microserver-howto#4]
The HOWTO doc implies `no` but the `--secure` script sets (likely properly) `without-password`:

Website says:

https://github.com/ntpsec/stratum-1-microserver-howto/blob/master/index.txt#L1023

Clockmaker does:

https://github.com/ntpsec/stratum-1-microserver-howto/blob/master/clockmaker#L423

**Comment by selsky** [comment]
Moved to https://gitlab.com/NTPsec/www/issues/12
